import type { ArchitectureModel, Intent, RepoFacts } from "../types"

export const sampleModel: ArchitectureModel = {
  version: 2,
  name: "umami-plumbing",
  repo: {
    id: "umami",
    github: "umami-software/umami",
  },
  groups: [
    {
      id: "next-app",
      label: "Umami · Next.js app (single deployable)",
      position: { x: 260, y: 0 },
      size: { width: 780, height: 640 },
    },
  ],
  nodes: [
    {
      id: "tracker",
      label: "Browser tracker",
      kind: "client",
      runtime: "browser",
      tech: ["typescript"],
      position: { x: 0, y: 120 },
      anchors: ["src/tracker/"],
    },
    {
      id: "ingest-api",
      label: "Collect API",
      kind: "api",
      runtime: "server",
      group: "next-app",
      tech: ["nextjs"],
      position: { x: 32, y: 48 },
      anchors: ["src/app/api/send/", "src/lib/detect.ts"],
    },
    {
      id: "sql-write",
      label: "Event writes",
      kind: "module",
      runtime: "server",
      group: "next-app",
      tech: ["prisma", "clickhouse"],
      position: { x: 32, y: 200 },
      anchors: [
        "src/queries/sql/**/save*.ts",
        "src/queries/sql/**/create*.ts",
        "src/queries/sql/**/update*.ts",
      ],
    },
    {
      id: "analytics-api",
      label: "Analytics API",
      kind: "api",
      runtime: "server",
      group: "next-app",
      tech: ["nextjs"],
      position: { x: 280, y: 48 },
      anchors: ["src/app/api/websites/"],
    },
    {
      id: "analytics-reads",
      label: "Analytics reads",
      kind: "module",
      runtime: "server",
      group: "next-app",
      tech: ["prisma", "clickhouse"],
      position: { x: 280, y: 200 },
      anchors: [
        "src/queries/sql/**/get*.ts",
        "src/queries/sql/**/extract*.ts",
      ],
    },
    {
      id: "dashboard-ui",
      label: "Dashboard UI",
      kind: "app",
      runtime: "server",
      group: "next-app",
      tech: ["react"],
      position: { x: 528, y: 48 },
      anchors: ["src/app/(main)/"],
    },
  ],
  edges: [
    {
      from: "tracker",
      to: "ingest-api",
      kind: "http",
      label: "POST /api/send · batch · record",
    },
    {
      from: "ingest-api",
      to: "sql-write",
      kind: "imports",
      label: "saveEvent · createSession",
    },
    {
      from: "dashboard-ui",
      to: "analytics-api",
      kind: "http",
      label: "GET /api/websites/:id/*",
    },
    {
      from: "analytics-api",
      to: "analytics-reads",
      kind: "imports",
      label: "get* query fns",
    },
  ],
}

export const botIngestIntent: Intent = {
  id: "bot-ingest",
  title: "Harden ingest bots — not the dashboard",
  allow: [
    "src/app/api/send/route.ts",
    "src/lib/detect.ts",
    "src/tracker/",
    "src/queries/sql/events/",
    "src/queries/sql/sessions/",
  ],
  deny: [
    "src/app/(main)/",
    "src/app/api/websites/",
    "src/queries/sql/getWebsiteStats.ts",
  ],
  strict: true,
  nodeIds: ["tracker", "ingest-api", "sql-write"],
  body: "Stay on ingest.",
}

export function umamiLikeFacts(overrides: Partial<RepoFacts> = {}): RepoFacts {
  return {
    packageJsonPaths: ["package.json"],
    dependencyNames: [
      "next",
      "react",
      "typescript",
      "prisma",
      "@prisma/client",
      "@clickhouse/client",
      "kafkajs",
      "redis",
      "@tanstack/react-query",
      "rrweb",
      "maxmind",
      "isbot",
      "zod",
      "zustand",
      "next-intl",
      "otplib",
      "@prisma/extension-read-replicas",
    ],
    prismaProvider: "postgresql",
    composeServices: [
      { name: "umami", image: "ghcr.io/umami-software/umami:latest", hasBuild: false },
      { name: "db", image: "postgres:15-alpine", hasBuild: false },
    ],
    hasNextConfig: true,
    hasDockerfile: true,
    hasDockerCompose: true,
    hasVercelJson: true,
    hasNetlifyToml: true,
    hasPrismaSchema: true,
    hasClickhouseSchema: true,
    hasKafkaTs: true,
    hasRedisTs: true,
    hasDbTs: true,
    hasTrackerIndex: true,
    hasRollupTracker: true,
    hasUseApi: true,
    hasQueriesDir: true,
    hasQueriesPrisma: true,
    hasQueriesSql: true,
    hasGithubDir: true,
    hasTsconfig: true,
    dbTsHasRunQuery: true,
    dbTsHasClickhouse: true,
    dbTsHasKafka: true,
    runQueryCallCount: 40,
    routeTsCount: 12,
    pageTsxCount: 8,
    routeGroupDirs: ["(main)", "(collect)"],
    writeQueryCount: 4,
    readQueryCount: 20,
    migrationHits: [
      "db/clickhouse/migrations/01.sql",
      "db/postgresql/data-migrations/x.sql",
    ],
    skipAuthRoutes: [
      "src/app/api/send/route.ts",
      "src/app/api/record/route.ts",
      "src/app/api/batch/route.ts",
      "src/app/api/config/route.ts",
    ],
    batchImportsSend: true,
    ingestUsesIsbot: true,
    hasReadReplica: true,
    redisHasRateLimit: true,
    realtimeIsJson: true,
    mcpUsesInProcessFetch: true,
    sendHasCollectors: true,
    subscriptionHasCloudLimits: true,
    composeProbesHeartbeat: true,
    ...overrides,
  }
}
